"""
traces_mcp.py — MCP server for TRACES portal integration.

Exposes TRACES (TDS Reconciliation Analysis and Correction Enabling System)
data as MCP tools for claude-for-ca TDS compliance plugin.

TRACES portal: traces.gov.in

Setup:
  pip install fastmcp requests

Credentials: Set TRACES_USERNAME, TRACES_PASSWORD, TRACES_TAN env vars.
NEVER hardcode credentials.
"""

import os
from typing import Optional

import requests
from fastmcp import FastMCP

TRACES_BASE_URL = "https://www.tdscpc.gov.in"

mcp = FastMCP("traces")

_session: Optional[requests.Session] = None


def _get_session() -> requests.Session:
    """
    Return an authenticated TRACES session.
    Note: TRACES uses form-based auth. In production, handle OTP/CAPTCHA.
    """
    global _session
    if _session is None:
        username = os.environ.get("TRACES_USERNAME")
        password = os.environ.get("TRACES_PASSWORD")
        tan = os.environ.get("TRACES_TAN")

        if not all([username, password, tan]):
            raise RuntimeError(
                "TRACES_USERNAME, TRACES_PASSWORD, and TRACES_TAN env vars must be set."
            )

        _session = requests.Session()
        # Note: Actual TRACES login requires handling CSRF tokens and potentially
        # OTP-based 2FA. This is a structural placeholder.
        # In production, use TRACES API credentials if available via income-tax.gov.in
        _session.headers.update({"User-Agent": "claude-for-ca TRACES MCP/1.0"})

    return _session


@mcp.tool()
def get_26as(
    pan: str,
    assessment_year: str,
) -> dict:
    """
    Fetch Form 26AS (Annual Information Statement) for a given PAN.

    Args:
        pan: PAN of the deductee (10-character alphanumeric)
        assessment_year: Assessment year in YYYY-YY format (e.g. "2025-26")

    Returns:
        Dict containing TDS/TCS details, advance tax, self-assessment tax paid.

    Note: 26AS is now integrated with AIS (Annual Information Statement) on
          income-tax.gov.in. This tool targets TRACES for TDS certificate data.
    """
    return {
        "pan": pan,
        "assessment_year": assessment_year,
        "part_a_tds": [],        # TDS deducted by deductors
        "part_b_tcs": [],        # TCS collected
        "part_c_advance_tax": [], # Advance tax / self-assessment tax
        "part_f_tds_refund": [],  # TDS refunds
        "note": "Connect to live TRACES/income-tax.gov.in for actual 26AS data.",
    }


@mcp.tool()
def get_tds_certificates(
    tan: str,
    financial_year: str,
    quarter: str,
    form_type: str = "26Q",
) -> dict:
    """
    Fetch TDS certificate details (Form 16A / Form 16) from TRACES.

    Args:
        tan: TAN of the deductor (10-character)
        financial_year: Financial year in YYYY-YY format (e.g. "2025-26")
        quarter: Quarter ("Q1", "Q2", "Q3", "Q4")
        form_type: "24Q" (salary) or "26Q" (non-salary). Default: "26Q"

    Returns:
        Dict with deductee-wise TDS certificate data.
    """
    return {
        "tan": tan,
        "financial_year": financial_year,
        "quarter": quarter,
        "form_type": form_type,
        "certificates": [],
        "note": "Connect to live TRACES for actual TDS certificate data. "
                "Use TRACES bulk download feature for large volumes.",
    }


@mcp.tool()
def get_csi_file(
    tan: str,
    financial_year: str,
    quarter: str,
) -> dict:
    """
    Download CSI (Challan Status Inquiry) file from TRACES for TDS return filing.

    Args:
        tan: TAN of the deductor
        financial_year: FY in YYYY-YY format
        quarter: Q1/Q2/Q3/Q4

    Returns:
        CSI file content (challan details needed for filing 24Q/26Q).
    """
    return {
        "tan": tan,
        "financial_year": financial_year,
        "quarter": quarter,
        "challans": [],
        "note": "CSI file download from TRACES. Used by TDS return filing software.",
    }


@mcp.tool()
def file_tds_return(
    tan: str,
    financial_year: str,
    quarter: str,
    form_type: str,
    fvu_file_path: str,
) -> dict:
    """
    File TDS return (24Q/26Q) on TRACES / TIN NSDL.

    ⚠️ THIS TOOL IS BLOCKED BY HITL HOOK — CA APPROVAL REQUIRED.
    The shared/hooks/hooks.json PreToolUse hook intercepts this call.

    Args:
        tan: TAN of the deductor
        financial_year: FY in YYYY-YY format
        quarter: Q1/Q2/Q3/Q4
        form_type: "24Q" or "26Q"
        fvu_file_path: Path to the validated FVU file generated by RPU software

    Returns:
        Filing status or HITL block message.
    """
    return {
        "status": "HITL_BLOCKED",
        "message": "TDS return filing requires explicit CA partner approval. "
                   "Approve via HITL prompt before this executes.",
        "tan": tan,
        "quarter": quarter,
        "form_type": form_type,
    }


if __name__ == "__main__":
    mcp.run()
